version: '3.1'

services:
  reconwithme-docs:
    image: retypeapp/retype:latest-debian
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    user: root:root
    ports:
      - "5000:5000"