version: '3.1'

services:
  reconwithme-docs:
    image: retypeapp/retype
    restart: always
    volumes:
      - .:/app
    ports:
      - 5000:80
    command: retype watch --host 0.0.0.0 --port 80 .